### ISSUE TITLE
Map Links in README.md broken.

### ISSUE THREAD

**Issue by gregtatum** [memoize-immutable/memoize-immutable#5]
Looks like they weren't updated when the packages were split out.

**Comment by louisremi** [comment]
Whoops,
Thanks for reporting this. I wrote the links without checking them. All Maps are here: https://github.com/memoize-immutable
I'll update the README :-)

**Comment by gregtatum** [comment]
Thanks :) Digging the work on this.

**Comment by louisremi** [comment]
I'm glad you like it! Please let me know if you decide to use it in a real project :-)

**Comment by gregtatum** [comment]
Sure thing, we're evaluating it for memoizing some derived data in our Redux connect functions that we want to keep local to the connected component.

https://github.com/devtools-html/perf.html
