### ISSUE TITLE
Does this work with ImmutableJS?

### ISSUE THREAD

**Issue by bscherminator** [memoize-immutable/memoize-immutable#6]
Is this good for using with ImmutableJS?

This is the top hit for googling `immutablejs memoize`, yet the docs here only specify requiring a browser which supports `WeakMap` and `Map` natively. This could be a bit clearer.

**Comment by louisremi** [comment]
Hello,

The library works perfectly with Immutablejs data structures, which are immutable. It will still only work in browsers that natively support `Map` and `WeakMap`, there's no way around it.
